//! Attaching doc comments to what they document. The lexer hands `##` and
//! `#!` lines over on the side ([`crate::lexer::lex_with_docs`]), so the
//! grammar never has to allow for them; the parser instead claims them by
//! position as it reaches each documentable item.
//!
//! A `##` block documents the item that starts right after it: only blank
//! lines and ordinary `#` comments may sit in between, since neither
//! produces a token. Items can be nested — a `pub const` generated by a
//! top-level `@for` is documented the same way as one written out — so
//! every statement block claims docs, not just the top level. A leading
//! `#!` block, before the file's first statement, documents the file.
//! Anything else documents nothing and ends up in
//! [`crate::ast::Program::stray_docs`] for the `unused_doc_comments` lint:
//! a `##` above something that isn't an item (an invocation, an `@emit`)
//! or at the end of a block or file, and a `#!` anywhere after the first
//! statement.

use crate::ast::{Doc, Statement};
use crate::token::{DocComment, TokenKind};

use super::Parser;

impl Parser {
    /// Claims the `#!` lines before the file's first token.
    pub(super) fn take_module_doc(&mut self) -> Option<Doc> {
        let start = self.current().span.start;
        let (module, rest): (Vec<_>, Vec<_>) = std::mem::take(&mut self.pending_docs)
            .into_iter()
            .partition(|doc| doc.is_module && doc.span.start < start);
        self.pending_docs = rest;
        Doc::from_lines(&module)
    }

    /// Claims the `##` block directly above the current token, the first
    /// token of an item. Doc comments further up, left behind inside the
    /// previous item (e.g. at the end of a macro body), are stray.
    pub(super) fn take_doc_lines(&mut self) -> Vec<DocComment> {
        let start = self.current().span.start;
        let floor = self.tokens[..self.pos]
            .iter()
            .rev()
            .find(|token| token.kind != TokenKind::Newline)
            .map_or(0, |token| token.span.end);

        let split = self.pending_docs.partition_point(|doc| doc.span.start < start);
        let mut block = Vec::new();
        for doc in self.pending_docs.drain(..split) {
            if doc.is_module || doc.span.start < floor {
                self.stray_docs.push(doc);
            } else {
                block.push(doc);
            }
        }
        block
    }

    pub(super) fn take_doc(&mut self) -> Option<Doc> {
        let lines = self.take_doc_lines();
        Doc::from_lines(&lines)
    }

    /// Gives `statement` the `##` block above it, or reports the block as
    /// stray if `statement` isn't something that can carry docs.
    pub(super) fn attach_doc(&mut self, statement: &mut Statement, lines: Vec<DocComment>) {
        let Some(doc) = Doc::from_lines(&lines) else { return };
        let slot = match statement {
            Statement::Struct(declaration) => &mut declaration.doc,
            Statement::Enum(declaration) => &mut declaration.doc,
            Statement::TypeAlias(declaration) => &mut declaration.doc,
            Statement::Const(declaration) => &mut declaration.doc,
            Statement::Macro(declaration) => &mut declaration.doc,
            Statement::Label(label) => &mut label.doc,
            Statement::SyntaxOverride(override_statement) => &mut override_statement.doc,
            Statement::Import(_)
            | Statement::ExternLabel(_)
            | Statement::Section(_)
            | Statement::Invocation(_)
            | Statement::Meta(_) => {
                self.stray_docs.extend(lines);
                return;
            }
        };
        *slot = Some(doc);
    }

    /// Everything never claimed, e.g. a `##` after the file's last item,
    /// with each run of adjacent lines merged into one entry so a stray
    /// paragraph is reported once rather than once per line.
    pub(super) fn finish_docs(&mut self) -> Vec<DocComment> {
        let mut stray = std::mem::take(&mut self.stray_docs);
        stray.append(&mut self.pending_docs);
        stray.sort_by_key(|doc| doc.span.start);

        let mut runs: Vec<DocComment> = Vec::new();
        for doc in stray {
            match runs.last_mut() {
                Some(run) if run.is_module == doc.is_module && !self.token_between(run.span.end, doc.span.start) => {
                    run.text.push('\n');
                    run.text.push_str(&doc.text);
                    run.span.end = doc.span.end;
                }
                _ => runs.push(doc),
            }
        }
        runs
    }

    fn token_between(&self, start: usize, end: usize) -> bool {
        let first = self.tokens.partition_point(|token| token.span.start < start);
        self.tokens[first..]
            .iter()
            .take_while(|token| token.span.start < end)
            .any(|token| token.kind != TokenKind::Newline)
    }
}
